image: docker:18-git

stages:
  - test
  - docker-build-staging
  - deploy-staging
  - docker-build-production

backend-unit-test:
  image: node:10
  stage: test
  only:
    refs:
      - merge_requests
  before_script:
    - npm install
  script:
    - npm run test:cov

backend-end-to-end-test:
  image: node:11
  stage: test
  only:
    refs:
      - master
  before_script:
    - npm install
  script:
    - npm run test:e2e


### STAGING ###
backend-docker-build-staging:
  stage: docker-build-staging
  services:
    - docker:18-dind
  only:
    refs:
      - master
  script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker build . -t waroenkumkm/backend:$CI_COMMIT_SHORT_SHA
    - docker push waroenkumkm/backend:$CI_COMMIT_SHORT_SHA

deploy-gcp:
  image: google/cloud-sdk
  stage: deploy-staging
  only:
    refs:
      - master
  before_script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - gcloud auth activate-service-account --key-file="$GCP_SERVICE_ACCOUNT"
    - gcloud config set project sound-abbey-292109
    - gcloud config set container/cluster waroenk-staging
    - gcloud config set compute/zone asia-southeast2-a
    - gcloud container clusters get-credentials waroenk-staging --zone asia-southeast2-a
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  script:
    - git clone https://$WAROENK_GITLAB_USERNAME:$WAROENK_GITLAB_PASSWORD@gitlab.com/waroenk-umkm/waroenk-infra.git kubernetes
    - cd kubernetes/gcp-staging/backend
    - sh ./env-staging.sh
    - kubectl apply -f backend-app.yaml


### PRODUCTION ###
backend-docker-build-production:
  stage: docker-build-production
  services:
    - docker:18-dind
  only:
    - tags
  script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker build . -t waroenkumkm/backend:$CI_COMMIT_TAG
    - docker push waroenkumkm/backend:$CI_COMMIT_TAG
