version: '3.7'

services:
  db:
    container_name: db
    image: mysql:8.0
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./scripts/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: waroenk
    ports:
      - 3306:3306

  keto-migrate:
    image: oryd/keto:v0.5.6
    environment:
      LOG_LEVEL: debug
    command:
      migrate sql mysql://root:12345@tcp(db:3306)/waroenk_permission
    restart: on-failure
    depends_on: 
      - db
  
  keto:
    image: oryd/keto:v0.5.6
    environment:
      LOG_LEVEL: debug
      DSN: mysql://root:12345@tcp(db:3306)/waroenk_permission
    ports: 
      - 4466:4466
    depends_on: 
      - keto-migrate
